/**
 * Test for Sheet Metal Contour Flange geometry generation
 * Validates that the feature correctly creates sweep profiles and geometries
 */

import { SheetMetalContourFlangeFeature } from '../features/sheetMetal/SheetMetalContourFlangeFeature.js';

export async function test_SheetMetalContourFlange_Basic(partHistory) {
  console.log("[TEST] Starting Sheet Metal Contour Flange basic test");
  
  // Create a simple L-shaped sketch path
  const plane = await partHistory.newFeature("P");
  plane.inputParams.orientation = "XY"; // XY plane at Z=0
  
  const sketch = await partHistory.newFeature("S");
  sketch.inputParams.sketchPlane = plane.inputParams.featureID;
  
  // Define L-shaped path: start at origin, go right 20 units, then up 15 units
  sketch.persistentData.sketch = {
    points: [
      { id: 0, x: 0, y: 0, fixed: true },     // Origin
      { id: 1, x: 20, y: 0, fixed: false },  // Right 20 units
      { id: 2, x: 20, y: 15, fixed: false }, // Up 15 units
    ],
    geometries: [
      { id: 100, type: "line", points: [0, 1], construction: false }, // Horizontal segment
      { id: 101, type: "line", points: [1, 2], construction: false }, // Vertical segment
    ],
    constraints: [
      { id: 0, type: "⏚", points: [0] }, // Ground point 0
    ],
  };
  
  // Create the contour flange
  const contourFlange = await partHistory.newFeature("SM.CF");
  contourFlange.inputParams.path = [sketch.inputParams.featureID];
  contourFlange.inputParams.distance = 10;    // 10 units wide
  contourFlange.inputParams.thickness = 2;    // 2 units thick
  contourFlange.inputParams.bendRadius = 1;   // 1 unit bend radius
  contourFlange.inputParams.sheetSide = "left";
  contourFlange.inputParams.consumePathSketch = false; // Keep sketch for inspection
  
  console.log("[TEST] Contour flange created:", contourFlange.inputParams);
  
  // Validate the generated geometry
  const result = partHistory.scene.children.filter(obj => 
    obj.name && obj.name.includes(contourFlange.inputParams.featureID)
  );
  
  console.log("[TEST] Generated objects:", result.length);
  
  if (result.length === 0) {
    throw new Error("No geometry was generated by the contour flange feature");
  }
  
  // Check that we have valid mesh geometry
  let totalVertices = 0;
  let totalTriangles = 0;
  
  for (const obj of result) {
    if (obj.isMesh && obj.geometry) {
      const pos = obj.geometry.getAttribute('position');
      if (pos) {
        totalVertices += pos.count;
        totalTriangles += obj.geometry.index ? obj.geometry.index.count / 3 : pos.count / 3;
      }
    }
  }
  
  console.log(`[TEST] Total vertices: ${totalVertices}, triangles: ${totalTriangles}`);
  
  if (totalVertices === 0) {
    throw new Error("Generated geometry has no vertices");
  }
  
  console.log("[TEST] Sheet Metal Contour Flange test passed!");
}

export async function test_SheetMetalContourFlange_StraightLine(partHistory) {
  console.log("[TEST] Starting Sheet Metal Contour Flange straight line test");
  
  // Create a simple straight line sketch
  const plane = await partHistory.newFeature("P");
  plane.inputParams.orientation = "XY";
  
  const sketch = await partHistory.newFeature("S");
  sketch.inputParams.sketchPlane = plane.inputParams.featureID;
  
  // Define straight line path
  sketch.persistentData.sketch = {
    points: [
      { id: 0, x: 0, y: 0, fixed: true },
      { id: 1, x: 30, y: 0, fixed: false },
    ],
    geometries: [
      { id: 100, type: "line", points: [0, 1], construction: false },
    ],
    constraints: [
      { id: 0, type: "⏚", points: [0] },
    ],
  };
  
  // Create the contour flange
  const contourFlange = await partHistory.newFeature("SM.CF");
  contourFlange.inputParams.path = [sketch.inputParams.featureID];
  contourFlange.inputParams.distance = 5;
  contourFlange.inputParams.thickness = 1;
  contourFlange.inputParams.bendRadius = 0; // No bends for straight line
  contourFlange.inputParams.sheetSide = "right";
  contourFlange.inputParams.consumePathSketch = false;
  
  console.log("[TEST] Straight line contour flange created");
  
  // Basic validation
  const result = partHistory.scene.children.filter(obj => 
    obj.name && obj.name.includes(contourFlange.inputParams.featureID)
  );
  
  if (result.length === 0) {
    throw new Error("No geometry generated for straight line contour flange");
  }
  
  console.log("[TEST] Straight line Sheet Metal Contour Flange test passed!");
}
